fix bug from recent commit: checks wrong executable when getting cmus art

diff --git a/scripts/fetch-art b/scripts/fetch-art
--- a/scripts/fetch-art
+++ b/scripts/fetch-art
@@ -29,8 +29,8 @@ elif [ "$source" = vlc ]; then
 
     url="$(playerctl -p vlc metadata mpris:artUrl)"
 elif [ "$source" = cmus ]; then
-    if ! command -v ffmpeg >/dev/null; then
-        echo "Missing ffmpeg!"
+    if ! command -v cmus-remote >/dev/null; then
+        echo "Missing cmus-remote!"
         exit 1
     fi
 
