add vlc support, and fixes multiple active players conflict bug.

diff --git a/scripts/fetch-art b/scripts/fetch-art
--- a/scripts/fetch-art
+++ b/scripts/fetch-art
@@ -21,9 +21,16 @@ if [ "$source" = spotify ]; then
     fi
 
     url="$(playerctl -p spotify metadata mpris:artUrl | sed 's;https://open.spotify.com;http://i.scdn.co;g')"
+elif [ "$source" = vlc ]; then
+    if ! command -v playerctl >/dev/null; then
+        echo "Missing playerctl!"
+        exit 1
+    fi
+
+    url="$(playerctl -p vlc metadata mpris:artUrl)"
 elif [ "$source" = cmus ]; then
-    if ! command -v cmus-remote >/dev/null; then
-        echo "Missing cmus-remote!"
+    if ! command -v ffmpeg >/dev/null; then
+        echo "Missing ffmpeg!"
         exit 1
     fi
 
